### ISSUE TITLE
Add HUSH

### ISSUE THREAD

**Issue by leto** [KomodoPlatform/komodo-ecosysboard#3]
The entire Hush github org would be best:

https://github.com/MyHush/

If that is not possible:

https://github.com/MyHush/hush
https://github.com/MyHush/hush3
https://github.com/MyHush/SilentDragon
https://github.com/MyHush/myhush.github.io
https://github.com/MyHush/librustzcash
https://github.com/MyHush/hush-v3-whitepaper
https://github.com/MyHush/myhushwallet
https://github.com/MyHush/insight-api-hush
https://github.com/MyHush/explorer.myhush.org
https://github.com/MyHush/hush-seeder
https://github.com/MyHush/hush-gitian
https://github.com/MyHush/Mediapack
https://github.com/MyHush/nspv_pywallet
https://github.com/leto/hushlist

**Comment by ca333** [comment]
@Milerius  based on
```
"coins": [
    {
      "coin": "kmd",
      "coin_paprika_id": "kmd-komodo",
      "git": []
    }
```
it should be possible to check the `git` array and if there is just **one** org URL instead of a repo URL then ecosys-board backend recursively fetches stats for all public repos of that org.

**Comment by leto** [comment]
@ca333 @Milerius  that sounds much nicer than keeping track of all these repos. Additionally, the backend should only cache the list of repos for a short time, and then refetch, so it can pick up new repos automatically

**Comment by Milerius** [comment]
Yeah it's will cache them at the end of the pull request.
